server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  banner:
    location: banner.txt
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: my-root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: "7g49bjlBG2cfSj4V6a5N9QW+voRYEXX0DjvJFeS4fPRfbGGzy2rzq3WvNvfeNvxC"