server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  banner:
    location: banner.txt
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: my-root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"