server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  banner:
    location: banner.txt
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: my-root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "ci927jBnQ4GsVEqj6ClN77nEFVMbcK4ZDq79UA6StkxWkOZVHGHNZc2HnjoUwiCX"
  valid-duration: 15 # in seconds
  refreshable-duration: 36000 # in seconds